import type { CaseStory } from '@/lib/stories';

/** Fallback stories when Supabase is not seeded — same content as seed_stories.sql */
export const FALLBACK_STORIES: CaseStory[] = [
    {
        id: 'fallback-1',
        slug: 'h1b-denial-rfe-approval',
        title_en: 'H-1B: From RFE to Approval After Initial Denial Intent',
        title_ru: 'H-1B: от RFE до одобрения после угрозы отказа',
        summary_en: 'A software engineer from India faced a specialty occupation RFE. Documenting degree equivalency led to approval.',
        summary_ru: 'Инженер из Индии получил RFE по specialty occupation. Документирование эквивалентности диплoma привело к одобрению.',
        story_en: 'Anonymized composite case. Raj (India, 29) received H-1B approval after an RFE questioning specialty occupation. He submitted credential evaluation, detailed employer letter, and project documentation. Approved 11 months from filing.',
        story_ru: 'Анонимизированный композит. Raj (Индия, 29) получил H-1B после RFE. Credential evaluation, письмо работодателя, документация проектов. Одобрение за 11 месяцев.',
        person_alias_en: 'Raj S., India',
        person_alias_ru: 'Raj S., Индия',
        origin_country: 'India',
        visa_types: ['H-1B', 'F-1'],
        tags: ['RFE', 'specialty occupation', 'credential evaluation', 'OPT'],
        outcome: 'approved',
        is_complex: true,
        lawyer_involved: true,
        duration_months: 11,
        lessons_learned_en: 'Never submit a minimal RFE response.',
        lessons_learned_ru: 'Никогда не отвечайте на RFE минимально.',
        key_takeaways_en: ['Credential evaluation before filing saves time', 'Employer letter must explain why degree is required'],
        key_takeaways_ru: ['Credential evaluation до подачи экономит время', 'Письмо работодателя должно объяснять необходимость диплoma'],
        published_at: '2025-07-06T00:00:00.000Z',
    },
    {
        id: 'fallback-2',
        slug: 'asylum-one-year-deadline',
        title_en: 'Asylum: Missing the One-Year Filing Deadline',
        title_ru: 'Убежище: пропуск годового срока',
        summary_en: 'A journalist succeeded with a changed circumstances exception after missing the 1-year deadline.',
        summary_ru: 'Журналист добился исключения changed circumstances после пропуска годового срока.',
        story_en: 'Anonymized composite. Elena (Honduras) filed asylum with changed circumstances exception after threats in 2022. Approved after 28 months with attorney help.',
        story_ru: 'Анонимизированный композит. Elena (Гондuras) подала asylum с исключением changed circumstances. Одобрение через 28 месяцев с адвокатом.',
        person_alias_en: 'Elena M., Honduras',
        person_alias_ru: 'Elena M., Гондuras',
        origin_country: 'Honduras',
        visa_types: ['ASYLUM', 'B-1/B-2'],
        tags: ['one-year deadline', 'changed circumstances', 'journalist', 'persecution'],
        outcome: 'approved',
        is_complex: true,
        lawyer_involved: true,
        duration_months: 28,
        lessons_learned_en: 'The one-year rule has exceptions.',
        lessons_learned_ru: 'Годовое правило имеет исключения.',
        key_takeaways_en: ['Changed circumstances exception is real but hard to prove'],
        key_takeaways_ru: ['Исключение changed circumstances реально, но сложно доказать'],
        published_at: '2025-07-06T00:00:00.000Z',
    },
    {
        id: 'fallback-3',
        slug: 'l1a-rfe-managerial-capacity',
        title_en: 'L-1A: RFE on Managerial Role and Proving Executive Duties',
        title_ru: 'L-1A: RFE о managerial role и доказательство executive duties',
        summary_en: 'A UK operations director faced an L-1A RFE on managerial capacity. Rebuilt org chart evidence led to approval.',
        summary_ru: 'Директор из UK получила RFE по L-1A о managerial capacity. Перестройка org chart привела к одобрению.',
        story_en: 'Anonymized composite. Sophie (UK, 38) received L-1A RFE arguing her role was functional, not managerial. Counsel rebuilt evidence with org charts, job descriptions, and payroll records. Approved in 7 months.',
        story_ru: 'Анонимизированный композит. Sophie (UK, 38) — RFE по L-1A: роль «functional». Org charts, job descriptions, payroll. Одобрение за 7 месяцев.',
        person_alias_en: 'Sophie W., United Kingdom',
        person_alias_ru: 'Sophie W., Великобритания',
        origin_country: 'United Kingdom',
        visa_types: ['L-1', 'EB-1'],
        tags: ['RFE', 'managerial capacity', 'blanket petition', 'intracompany transfer'],
        outcome: 'approved',
        is_complex: true,
        lawyer_involved: true,
        duration_months: 7,
        lessons_learned_en: 'L-1A job descriptions written by HR often trigger RFEs.',
        lessons_learned_ru: 'Job descriptions для L-1A от HR часто вызывают RFE.',
        key_takeaways_en: ['Org charts must show a real management chain', 'Avoid hybrid IC language in L-1A petitions'],
        key_takeaways_ru: ['Org charts должны показывать цепочку управления', 'Избегайте IC-формулировок в L-1A'],
        published_at: '2025-07-06T00:00:00.000Z',
    },
    {
        id: 'fallback-4',
        slug: 'eb2-niw-stem-self-petition',
        title_en: 'EB-2 NIW: Self-Petition Without Employer Sponsor',
        title_ru: 'EB-2 NIW: self-petition без спонсора-работодателя',
        summary_en: 'A South Korean researcher self-petitioned EB-2 NIW with publications and national importance evidence. I-140 approved without PERM.',
        summary_ru: 'Исследователь из Южной Кореи подала EB-2 NIW self-petition с публикациями и national importance. I-140 одобрен без PERM.',
        story_en: 'Anonymized composite. Dr. Kim (South Korea, 34) filed EB-2 NIW after employer declined PERM. Matter of Dhanasar evidence with RFE response. I-140 approved in 11 months.',
        story_ru: 'Анонимизированный композит. Dr. Kim (Южная Корея, 34) — EB-2 NIW после отказа PERM. Matter of Dhanasar, RFE. I-140 за 11 месяцев.',
        person_alias_en: 'Dr. Kim H., South Korea',
        person_alias_ru: 'Dr. Kim H., Южная Корея',
        origin_country: 'South Korea',
        visa_types: ['EB-2', 'H-1B', 'J-1'],
        tags: ['NIW', 'self-petition', 'PERM waiver', 'RFE', 'STEM'],
        outcome: 'approved',
        is_complex: true,
        lawyer_involved: true,
        duration_months: 11,
        lessons_learned_en: 'NIW is not easier than PERM — it replaces labor certification with a harder evidence standard.',
        lessons_learned_ru: 'NIW не проще PERM — нужен более высокий стандарт доказательств.',
        key_takeaways_en: ['Self-petition removes employer dependency', 'RFEs often ask for endeavor specificity'],
        key_takeaways_ru: ['Self-petition снимает зависимость от работодателя', 'RFE требуют конкретики endeavor'],
        published_at: '2025-07-06T00:00:00.000Z',
    },
    {
        id: 'fallback-5',
        slug: 'j1-waiver-212e-h1b-path',
        title_en: 'J-1: 212(e) Home Residency Waiver and Transition to H-1B',
        title_ru: 'J-1: waiver 212(e) home residency и переход на H-1B',
        summary_en: 'A Chinese research scholar obtained a J-1 IGA waiver, then changed to cap-exempt H-1B.',
        summary_ru: 'Китайский research scholar получил J-1 IGA waiver, затем сменил статус на cap-exempt H-1B.',
        story_en: 'Anonymized composite. Wei (China, 31) had 212(e) on DS-2019. IGA waiver via NIH took 14 months, then H-1B change-of-status in 4 months. Total: 18 months.',
        story_ru: 'Анонимизированный композит. Wei (Китай, 31) — 212(e) на DS-2019. IGA waiver 14 месяцев, H-1B change-of-status 4 месяца. Итого: 18 месяцев.',
        person_alias_en: 'Wei L., China',
        person_alias_ru: 'Wei L., Китай',
        origin_country: 'China',
        visa_types: ['J-1', 'H-1B'],
        tags: ['212(e)', 'home residency', 'J-1 waiver', 'IGA', 'change of status'],
        outcome: 'approved',
        is_complex: true,
        lawyer_involved: true,
        duration_months: 18,
        lessons_learned_en: 'Check DS-2019 for 212(e) before accepting any U.S. job offer.',
        lessons_learned_ru: 'Проверяйте DS-2019 на 212(e) до принятия job offer.',
        key_takeaways_en: ['IGA waivers can take over a year', 'Never work before status change is approved'],
        key_takeaways_ru: ['IGA waivers могут занять больше года', 'Не работайте до approval смены статуса'],
        published_at: '2025-07-06T00:00:00.000Z',
    },
    {
        id: 'fallback-6',
        slug: 'tn-mexico-engineer-denied-then-approved',
        title_en: 'TN: Initial Denial for Job Title Mismatch, Approved on Reapplication',
        title_ru: 'TN: первоначальный отказ из-за job title, одобрение при повторной подаче',
        summary_en: 'A Mexican engineer was denied TN at the border for job title mismatch, then approved after revising the offer letter.',
        summary_ru: 'Мексиканский инженер получил отказ TN на границе из-за job title, затем одобрение после исправления offer letter.',
        story_en: 'Anonymized composite. Diego (Mexico, 27) denied TN because title was "Product Development Specialist." Revised to "Mechanical Engineer" with USMCA-aligned duties. Approved on second try.',
        story_ru: 'Анонимизированный композит. Diego (Мексика, 27) — отказ TN из-за title. Исправлен offer letter. Одобрение при второй подаче.',
        person_alias_en: 'Diego M., Mexico',
        person_alias_ru: 'Diego M., Мексика',
        origin_country: 'Mexico',
        visa_types: ['TN'],
        tags: ['USMCA', 'job title', 'border application', 'denial'],
        outcome: 'approved',
        is_complex: false,
        lawyer_involved: false,
        duration_months: 4,
        lessons_learned_en: 'TN approvals live or die on profession list alignment.',
        lessons_learned_ru: 'TN одобряют или отказывают по profession list.',
        key_takeaways_en: ['Creative job titles hurt TN applications', 'Withdrawal is often better than arguing at the port'],
        key_takeaways_ru: ['Креативные job titles вредят TN', 'Withdrawal часто лучше спора на порту'],
        published_at: '2025-07-06T00:00:00.000Z',
    },
    {
        id: 'fallback-7',
        slug: 'u-visa-certification-green-card-path',
        title_en: 'U Visa: Law Enforcement Certification and the Path to Adjustment',
        title_ru: 'U visa: law enforcement certification и путь к adjustment',
        summary_en: 'A domestic violence survivor obtained U status after delayed certification, then adjusted to green card.',
        summary_ru: 'Выжившая после domestic violence получила U status после задержки certification, затем green card.',
        story_en: 'Anonymized composite. Ana (Guatemala, 30) obtained Supplement B certification after advocacy, waited 4 years in cap backlog, then adjusted to LPR. Total: 9 years.',
        story_ru: 'Анонимизированный композит. Ana (Гватемала, 30) — certification после advocacy, cap backlog 4 года, adjustment до LPR. Итого: 9 лет.',
        person_alias_en: 'Ana G., Guatemala',
        person_alias_ru: 'Ana G., Гватемала',
        origin_country: 'Guatemala',
        visa_types: ['U'],
        tags: ['U visa', 'law enforcement certification', 'I-918', 'adjustment of status', 'EAD'],
        outcome: 'approved',
        is_complex: true,
        lawyer_involved: true,
        duration_months: 108,
        lessons_learned_en: 'U visa cases are multi-year journeys. Start certification early.',
        lessons_learned_ru: 'U visa — путь на годы. Начинайте certification рано.',
        key_takeaways_en: ['Supplement B certification can take advocacy to obtain', 'EAD during wait allows lawful work'],
        key_takeaways_ru: ['Supplement B может потребовать advocacy', 'EAD на время ожидания даёт lawful work'],
        published_at: '2025-07-06T00:00:00.000Z',
    },
    {
        id: 'fallback-8',
        slug: 'dv-lottery-consular-interview-221g',
        title_en: 'DV Lottery: Selectee Navigating 221(g) and Document Review',
        title_ru: 'DV Lottery: selectee проходит 221(g) и проверку документов',
        summary_en: 'An Egyptian DV winner received 221(g) for missing police certificates, then obtained a visa after submitting complete records.',
        summary_ru: 'Победитель DV из Египта получил 221(g) из-за police certificates, затем визу после полного пакета.',
        story_en: 'Anonymized composite. Hassan (Egypt, 29) received 221(g) at Cairo interview for missing police certificate and name transliteration mismatch. Visa issued 11 weeks later. Entry in 16 months from selection.',
        story_ru: 'Анонимизированный композит. Hassan (Египет, 29) — 221(g) в Cairo. Visa через 11 недель. Въезд за 16 месяцев от selection.',
        person_alias_en: 'Hassan A., Egypt',
        person_alias_ru: 'Hassan A., Египет',
        origin_country: 'Egypt',
        visa_types: ['DV'],
        tags: ['DV lottery', '221(g)', 'consular interview', 'police certificate'],
        outcome: 'approved',
        is_complex: false,
        lawyer_involved: false,
        duration_months: 16,
        lessons_learned_en: 'DV selectees win a narrow window — treat 221(g) as a checklist fix, not a denial.',
        lessons_learned_ru: 'DV selectees имеют узкое окно — 221(g) это checklist fix, а не отказ.',
        key_takeaways_en: ['Collect police certificates from every jurisdiction you lived in', 'Track fiscal year deadlines obsessively'],
        key_takeaways_ru: ['Police certificates из каждого места жительства', 'Следите за fiscal year deadlines'],
        published_at: '2025-07-06T00:00:00.000Z',
    },
];
